language: java
jdk:
  - openjdk8

branches:
  only: # 오직 master브랜치에 push될때만 수행됩니다.
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 PUSH 되었을때 수행하는 명령어입니다
# 여기선 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다.

# CI 실행 완료시 메일로 알람
notifications:
  email: # Email외에도 Slack이 있으니, 관심있으신 분들은 링크1, 링크2를 참고하여 Slack도 추가하시는걸 추천드립니다.
    recipients:
      - s2017i30@e-mirim.hs.kr