language: java
  jdk:
    - openjdk8

  branches: # 브랜치는 master에만 했을 때 !!!! 만 돌아가게 !!
    only:
      - master

  # Travis CI 서버의 Home
  cache:
    directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

  script: "./gradlew clean build" # 스크립트가 푸시가 됐을 때 실행시킬 명령어
  # 이전에 있었던거 지우고 실행시키기 !!!! (out 폴더~~!!!)

  # CI 실행 완료시 메일로 알람
  notifications:
    email:
      recipients:
        - s2017i30@e-mirim.hs.kr