language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r Squirrel *
  - mkdir -p deploy
  - mv Squirrel.zip deploy/Squirrel.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: squirrel-webservice-bucket # 6-3-3에서 생성한 S3 버킷
    local_dir: deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: shinsunyoung/Squirrel #Github 주소
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - s2017i30@e-mirim.hs.kr